### ISSUE TITLE
Luck with ventura 13.6?

### ISSUE THREAD

**Issue by pcace** [dclive/B660M-HDV-i5-12400F-Hackintosh#12]
Hi, 

have you had any luck with ventura 13.6 too? 

Thanks a lot!

**Comment by dclive** [comment]
As I wrote, a power issue destroyed the Asrock B660M-HDV. 

Risk to go to 13.6 or 14.0 should approach zero, though.  13.6 is trivial; 14.0 may require some fiddling to get the wifi working, if you’re using it.

**Comment by pcace** [comment]
Hi, thanks a lot for your reply! The reason i am asking is that i can install it flawlessly, but after the initial install, when booting the first time using oc from the install stick, i am running into a strange restart loop and cannot figure out what the issue might be. 

maybe you have had this too? 

![IMG_3370](https://github.com/dclive/B660M-HDV-i5-12400F-Hackintosh/assets/1011875/13c58971-803a-4911-b1c2-282ac27cabbb)

**Comment by pcace** [comment]
Solved: secureboot needed to be disabled completely in config.plist
